version: '3'

services:
  investimentos-db:
    image: ${DOCKER_DB_IMAGE}
    container_name: ${DOCKER_DB_CONTAINER_NAME}
    ports:
      - ${DOCKER_DB_PORTS}
    volumes:
      - ${DOCKER_DB_VOLUMES}
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_DB_DATABASE}
volumes:
  investimentos:
